### ISSUE TITLE
请求https://m.weibo.cn/feed/friends?version=v4不行？

### ISSUE THREAD

**Issue by 70kg** [ruansongsong/nodejs-weibo-login#1]
用获取的cookie去请求这个这地址不行,其他的类似 https://m.weibo.cn/api/comments/show?id=4120428048490761&page=1 这个地址是可以的。首页的cookie做了什么限制吗？几个月之前首页也是正常的，现在就不行了。

**Comment by ruansongsong** [comment]
你请求的是移动端微博，移动端微博和电脑网页版微博的登录机制是不一样的，我这个只适合电脑网页微博的模拟登录。

**Comment by ruansongsong** [comment]
不知道微博移动端和网页端的cookie机制是不是一样的
